### ISSUE TITLE
Consider allowing multiple instances of the same job to run at once

### ISSUE THREAD

**Issue by nickdaugherty** [Automattic/Cron-Control#106]
On sites that queue up many of the same type of job, only running one at a time can cause large backlogs, depending on volume.

Should we allow up to the max global concurrency, dropping the per-event lock? Or, allow tweaking the per-event rate limiter on a per-event basis. The former is more set-and-forget.

**Comment by ethitter** [comment]
It'll have to be a per-event increase in the limit, at least to start. We might eventually be able to move to a blacklist of events than can only run serially, but it's problematic to allow any event to run concurrently with another instance of itself. As I discovered during plugin development, and perhaps largely due to the fun that is alloptions, running several of the same event simultaneously led to events overwriting each other's updates to options, among other issues.

I do agree that something needs to be done to help compensate for large queues. Another idea I explored is adjusting how events are queued, as we're prone to stampeding the event locks right now, which exacerbates the issue. The change would introduce some small delay between events with the same action, when those events don't have a far-future timestamp. I started toying with this in D5251-code, but it needs work. The approach is only potentially viable because the events that backlog so far have been ones that execute quickly (generally less than a second), but a large queue of slow events won't be helped by this approach.
