### ISSUE TITLE
Set short timestamp on error

### ISSUE THREAD

**Issue by ethitter** [Automattic/Cron-Control#135]
Rather than mocking that event execution is disabled indefinitely, use a near-term timestamp to ensure runner doesn't stop for too long.

https://github.com/Automattic/Cron-Control/blob/77c2e840438c6ca14870ba4bec33c676af855289/runner/runner.go#L150

**Comment by WPprodigy** [comment]
The new runner will continue with it's "getSites" interval even on error: https://github.com/Automattic/cron-control-runner/blob/7504e921e06595bf2b0e0fc97febdd1aed4c0369/orchestrator/orchestrator.go#L95-L96

Since site-listing is less of a requirement for overall event fetching/running now, this can happen in like ~60seconds intervals. hitting the site once a minute to see if it's working again feels sufficient - not too heavy and not too infrequent.
